<a href="https://colab.research.google.com/github/sunilsinghuk/Python-Programming/blob/main/L3_4_Indexing_Slicing_Array_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lecture 3: Indexing, Slicing, and Manipulating Arrays**
## **Indexing and Slicing (30 mins)**
* Accessing individual elements in 1D, 2D, and multi-dimensional arrays.
* Slicing arrays using ranges.
* Fancy indexing and boolean indexing.
## **Manipulating Arrays (30 mins)**
* Reshaping arrays with reshape() and ravel().
* Adding and removing dimensions using newaxis() and squeeze().
* Stacking and splitting arrays (vstack(), hstack(), split()).

# **Lecture 4: Array Operations and Broadcasting**
## **Array Operations (30 mins)**
* Element-wise operations (addition, subtraction, multiplication, division).
* Applying universal functions (np.exp, np.sqrt, etc.).
## **Broadcasting (30 mins)**
* Understanding broadcasting rules.
* Examples of broadcasting in operations.




# **Lecture 2: Indexing, Slicing, and Manipulating Arrays**

## **1. Indexing and Slicing**

* Accessing Individual Elements in Arrays

NumPy allows you to access individual elements in 1D, 2D, and multi-dimensional arrays using indexing.

**1D Array Indexing**

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # Output: 10
print(arr[2])  # Output: 30
print(arr[-1]) # Output: 50 (Last element)

10
30
50


**Explanation:** We access elements using their index, starting from 0. Negative indexing helps access elements from the end.

**2D Array Indexing**

In [2]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print(arr2d[0, 0])  # Output: 1
print(arr2d[1, 2])  # Output: 6
print(arr2d[-1, -1]) # Output: 9

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
6
9


**Explanation:** Use [row, column] notation to access elements. Negative indices select from the end.


**3D Array Indexing**

In [5]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d)
print(arr3d[0, 1, 1])  # Output: 4


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4


**Explanation:** In a 3D array, indexing follows [depth, row, column] order.

## **Slicing Arrays Using Ranges**

**1D Array Slicing**

In [6]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # Output: [20, 30, 40]
print(arr[:3])   # Output: [10, 20, 30]
print(arr[::2])  # Output: [10, 30, 50] (Every second element)

[20 30 40]
[10 20 30]
[10 30 50]


**Explanation:** Slicing is done using **[start:end:step]**. **Default start is 0, default end is last, and default step is 1.**

**2D Array Slicing**

In [10]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print(arr2d[0:2, 1:3])  # Output: [[2, 3], [5, 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


**Explanation:** We extract a submatrix using **[row_start:row_end, col_start:col_end]** notation.

### **Fancy Indexing and Boolean Indexing**

* Fancy Indexing (Using lists or arrays for specific indexes)

In [17]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 2, 4]])  # Output: [10, 30, 50] start:step:end

[10 30 50]


**Explanation:** We pass a list of indices to extract specific elements.

**Boolean Indexing**

In [18]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])  # Output: [30, 40, 50]

[30 40 50]


**Explanation:** We use boolean conditions to filter values.

## **2. Manipulating Arrays**

**Reshaping Arrays**

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


**Explanation:** reshape() modifies the shape without changing data.

### **Flattening Arrays with ravel()**

In [ ]:
print(reshaped.ravel())  # Output: [1, 2, 3, 4, 5, 6]

**Explanation:** ravel() flattens an array into 1D.

**Adding and Removing Dimensions**

In [23]:
arr = np.array([1, 2, 3])
print(arr[:, np.newaxis])  # Adds new dimension

[[1]
 [2]
 [3]]


**Explanation:** newaxis adds an extra dimension to the array.

**Stacking and Splitting Arrays**

In [24]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.vstack((arr1, arr2)))  # Vertical stack
print(np.hstack((arr1, arr2)))  # Horizontal stack

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


**Explanation:** vstack() stacks vertically, hstack() stacks horizontally.