<a href="https://colab.research.google.com/github/sunilsinghuk/Python-Programming/blob/main/L7_8_Statistical_Fun_and_Linear_Algebra_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lecture 7: Statistical Functions**
### **1. Introduction to Statistical Functions (15 mins)**
**Why are statistical functions important in data analysis?**

Statistical functions are crucial for summarizing and analyzing datasets. They help in:

* Understanding the distribution of data.
* Identifying trends and patterns.
* Performing feature engineering in machine learning.
* Making data-driven decisions.

### **2. Core Statistical Functions (30 mins)**
**1. Mean (np.mean())**

***The mean (average)*** is the sum of all elements divided by the total number of elements.

**Example:**

In [ ]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])
mean_value = np.mean(data)
print("Mean:", mean_value)

Mean: 30.0


**Explanation:** The mean is calculated as (10+20+30+40+50)/5 = 30.

**2. Median (np.median())**

The median is the middle value when the numbers are arranged in order.

**Example:**

In [ ]:
data = np.array([10, 20, 30, 40, 50])
median_value = np.median(data)
print("Median:", median_value)

Median: 30.0


**3. Variance (np.var())**
Variance measures how much the data deviates from the mean.

**Example:**

In [ ]:
data = np.array([10, 20, 30, 40, 50])
variance_value = np.var(data)
print("Variance:", variance_value)

Variance: 200.0


**Explanation:** A low variance means data points are close to the mean, while a high variance indicates spread-out data.

**4. Standard Deviation (np.std())**

The standard deviation is the square root of the variance and represents the spread of data.

**Example:**

In [ ]:
std_dev = np.std(data)
print("Standard Deviation:", std_dev)


Standard Deviation: 14.142135623730951


**Explanation:** A higher standard deviation indicates more variation in the dataset.

## **3. Other Statistical Functions**
**1. Percentile (np.percentile())**

Percentiles help in understanding the distribution of data.

**Example:** Find the 50th percentile (median) and 90th percentile.

In [ ]:
percentile_50 = np.percentile(data, 50)
percentile_90 = np.percentile(data, 90)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)

50th Percentile (Median): 30.0
90th Percentile: 46.0


**Explanation:** This tells us how many values are below a certain threshold.

**2. Correlation Coefficient (np.corrcoef())**

Shows the relationship between two datasets.

In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])
correlation = np.corrcoef(x, y)
print("Correlation Coefficient:\n", correlation)

Correlation Coefficient:
 [[1. 1.]
 [1. 1.]]


**Explanation:** A coefficient close to 1 indicates a strong positive correlation.

**3. Histogram (np.histogram())**

Used for understanding frequency distribution.

In [ ]:
hist, bins = np.histogram(data, bins=5)
print("Histogram:", hist)
print("Bins:", bins)

Histogram: [1 1 1 1 1]
Bins: [10. 18. 26. 34. 42. 50.]


**Explanation:** Helps in visualizing how data is distributed.

### **Understanding Histogram and Bins in NumPy**
**What is a Histogram?**

A histogram is a **way of representing the frequency distribution of numerical data.** It divides the entire range of values into **intervals (bins)** and counts how many values fall into each bin.

Used in statistics and data visualization to understand how data is distributed.
Helps identify patterns like normal distribution, skewness, or uniform distribution.

**What are Bins in a Histogram?**

**Bins are the intervals** that divide the range of data.
The number of bins determines how granular the histogram will be.
More bins = More detailed distribution, fewer bins = more generalized view.

**Example in NumPy: Creating a Histogram**

Let's create a histogram for a dataset and see how bins work.

In [ ]:
import numpy as np

# Sample data: Scores of students in an exam
data = np.array([45, 47, 50, 55, 60, 62, 65, 68, 70, 75, 78, 80, 82, 85, 90])

# Creating histogram with 5 bins
hist, bins = np.histogram(data, bins=5)

print("Histogram:", hist)  # Frequency count per bin
print("Bins:", bins)  # Bin edges


Histogram: [3 3 3 3 3]
Bins: [45. 54. 63. 72. 81. 90.]


**Explanation**
* np.histogram(data, bins=5) divides the data into 5 equal intervals (bins).
* hist gives the count of values in each bin.
* bins shows the range of each bin.


**Understanding Output**

If the output is:

Histogram: [3 3 4 3 2]

Bins: [45. 54. 63. 72. 81. 90.]

**Bins: [45. 54. 63. 72. 81. 90.]**

* The first bin includes values from 45 to 54.
* The second bin includes values from 54 to 63, and so on.

**Histogram: [3 3 4 3 2]**

* 3 values (45, 47, 50) fall between 45-54
* 3 values (55, 60, 62) fall between 54-63
* 4 values (65, 68, 70, 75) fall between 63-72
* 3 values (78, 80, 82) fall between 72-81
* 2 values (85, 90) fall between 81-90


### **4. Hands-on Practice (15 mins)**
* Compute mean, median, variance, and standard deviation for a dataset.
* Find correlation between two data variables.
* Visualize data distribution using a histogram.

# **Lecture 6: Linear Algebra with NumPy**
## **1. Linear Algebra Basics (15 mins)**
**Why is linear algebra important in data analysis?**
* Used in machine learning, deep learning, and optimization problems.
* Helps in transformations and handling large datasets.
* Essential for operations on multidimensional arrays and matrices.

## **2. Core Linear Algebra Functions (30 mins)**
**1. Dot Product (np.dot())**

The dot product is the sum of the element-wise multiplication of two arrays.




In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Dot Product:", dot_product)

Dot Product: 32


**2. Matrix Multiplication (np.matmul())**

Used for multiplying matrices in deep learning.

**Explanation:** Standard row-column multiplication of matrices.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
matrix_product = np.matmul(A, B)
print("Matrix Multiplication:\n", matrix_product)

Matrix Multiplication:
 [[19 22]
 [43 50]]


**3. Transpose (np.transpose())**

Flips a matrix over its diagonal.

**Explanation:** The rows become columns and vice versa.

In [ ]:
A = np.array([[1, 2], [3, 4]])
transpose_A = np.transpose(A)
print(A)
print("Transpose:\n", transpose_A)

[[1 2]
 [3 4]]
Transpose:
 [[1 3]
 [2 4]]


**4. Inverse of a Matrix (np.linalg.inv())**

Used in solving equations and transformations.

**Explanation:** The inverse of a matrix A is A⁻¹ such that A × A⁻¹ = Identity Matrix.


In [ ]:
A = np.array([[1, 2], [3, 4]])
inverse_A = np.linalg.inv(A)
print(A)
print("Inverse:\n", inverse_A)

[[1 2]
 [3 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


**5. Eigenvalues and Eigenvectors (np.linalg.eig())**

Important in PCA, dimensionality reduction.

**Explanation:** Eigenvalues describe the magnitude of transformation, while eigenvectors represent the direction.

In [ ]:
A = np.array([[2, -1], [-1, 2]])
print(A)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


[[ 2 -1]
 [-1  2]]
Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


## **3. Hands-on Practice (15 mins)**
* Perform dot product and matrix multiplication.
* Compute the inverse and transpose of a matrix.
* Find eigenvalues and eigenvectors of a given matrix.

# **General Tips for Effective Learning for Students**
✅ Start with Basics & Build Up Gradually

* Begin with simple concepts before moving to advanced topics.
* Understand fundamental principles before applying them in complex scenarios.

✅ **Explore Official Documentation**

* NumPy, Pandas, and other libraries have well-documented official guides.
* Encourage students to **refer to NumPy Documentation for deeper understanding.**

✅ Hands-on Practice is Key

* Apply what you learn with real datasets and coding exercises.
* Experiment with different functions and methods to see how they work.

✅ Break Problems into Smaller Steps

* When facing a complex problem, break it down into smaller, manageable parts.
* Solve step by step rather than tackling everything at once.


✅ Engage in Group Discussions & Peer Learning

* Explaining concepts to peers reinforces understanding.
* Group discussions help in gaining multiple perspectives on problem-solving.

✅ Practice with Real-World Datasets

* Work on datasets related to business, healthcare, or finance to see practical applications.
* Kaggle and Google Colab provide free datasets for practice.

✅ Learn Debugging & Error Handling

* Instead of fearing errors, analyze them and learn from them.
* Use print statements or debugging tools to track issues in your code.

✅ Stay Curious & Keep Exploring

* Go beyond the classroom—explore advanced topics, tutorials, and research papers.
* Follow tech blogs, YouTube channels, or participate in coding competitions.

✅ Time Management & Consistency

* Set a study schedule and stick to it to maintain consistency.
* Daily practice, even for 30 minutes, is better than last-minute cramming.